version: "3"

services:
  bookish-web:
    # We want to copy the .jar from /target, so we need to use the current
    # directory as build context root to have access to /target
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    environment:
      - DB_HOSTNAME=bookish-database
      - DB_PASSWORD=SuperSecretPassword
    ports:
      - "8080:8080"
    depends_on:
      - bookish-database
  bookish-database:
    build: ./docker/database
    environment:
      - MYSQL_ROOT_PASSWORD=SuperSecretPassword
